#!/bin/env sh

dir=data/plexi/V5/kg5
d=7.7
D=15.2

V=5
m=5

(
    cat $dir/t1.csv | julia --project=. scripts/prepare_data.jl | julia --project=. scripts/calc_data.jl -d $d -D $D -V $V -m $m --startt 4 --stopt 12.0 --MBR=0.2
    cat $dir/t2.csv | julia --project=. scripts/prepare_data.jl | julia --project=. scripts/calc_data.jl -d $d -D $D -V $V -m $m --startt 10 --stopt 15 --MBR=0.2
    cat $dir/t3.csv | julia --project=. scripts/prepare_data.jl | julia --project=. scripts/calc_data.jl -d $d -D $D -V $V -m $m --startt 10 --stopt 19.0 --MBR=0.2
) | julia --project=. scripts/lines_mean.jl
